# inherit from the proprietary version
-include vendor/lge/esteem/BoardConfigVendor.mk

TARGET_SPECIFIC_HEADER_PATH := device/lge/esteem/include

TARGET_NO_BOOTLOADER := true

TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

## ARMv7 Processor rev 2 (v7l)
TARGET_CPU_ABI := armeabi
TARGET_CPU_ABI2 := armeabi-v7a
TARGET_ARCH_VARIANT := armv7-a-neon

TARGET_BOOTLOADER_BOARD_NAME := esteem
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_USES_2G_VM_SPLIT := true

BOARD_KERNEL_CMDLINE := console=ttyMSM1 androidboot.hardware=bryce
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_PAGE_SIZE := 2048

TARGET_PREBUILT_KERNEL := device/lge/esteem/kernel

## Partition sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1031798784
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1610612736
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_USES_MMCUTILS := true

# Filesystem
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p12
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_DATA_DEVICE := /dev/block/mmcblk0p13
BOARD_DATA_FILESYSTEM := ext4
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p6
BOARD_CACHE_FILESYSTEM := ext4
BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk1p1
BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1
BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p2
BOARD_HAS_NO_MISC_PARTITION := true
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_HAS_SDCARD_INTERNAL := true

# Recovery
TARGET_PREBUILT_RECOVERY_KERNEL := device/lge/esteem/recovery/recovery_kernel
BOARD_CUSTOM_GRAPHICS := ../../../device/lge/esteem/recovery/graphics.c
BOARD_HAS_NO_SELECT_BUTTON := true

# USB
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
BOARD_UMS_LUNFILE := "/sys/devices/platform/usb_mass_storage/lun0/file"

# Wifi related defines
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WPA_SUPPLICANT_VERSION      := VER_0_6_X
BOARD_WLAN_DEVICE           := bcm4329
WIFI_DRIVER_MODULE_PATH     := "/system/lib/modules/bcm4329.ko"
WIFI_DRIVER_FW_STA_PATH     := "/vendor/firmware/fw_bcm4329.bin"
WIFI_DRIVER_FW_AP_PATH      := "/vendor/firmware/fw_bcm4329_apsta.bin"
WIFI_DRIVER_MODULE_ARG      := "firmware_path=/vendor/firmware/fw_bcm4329.bin nvram_path=/proc/calibration"
WIFI_DRIVER_MODULE_NAME     := "bcm4329"

# Audio
BOARD_USES_GENERIC_AUDIO := false

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_AMSS_VERSION := 6225
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000

# qcom
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
BOARD_USE_QCOM_PMEM := true

# Graphics
BOARD_USES_ADRENO_200 := true
#BOARD_USE_LEGACY_TOUCHSCREEN := true
#BOARD_EGL_CFG := device/lge/esteem/prebuilt/lib/egl/egl.cfg
#BOARD_OVERLAY_FORMAT_YCbCr_420_SP := true
#USE_OPENGL_RENDERER := true
BOARD_USES_GENLOCK := true
#BOARD_NO_RGBX_8888 := false
#TARGET_USES_OVERLAY := true
#COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60
#TARGET_FORCE_CPU_UPLOAD := true
TARGET_QCOM_HDMI_OUT := true
#BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true

# Camera
BOARD_CAMERA_USE_GETBUFFERINFO := true

# FM Radio
BOARD_HAVE_FM_RADIO := true
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

# Misc
ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=0
TARGET_OTA_ASSERT_DEVICE := esteem,bryce,MS910