

# Build openGL 2.0
include $(CLEAR_VARS)
LOCAL_PATH := $(THIS_PATH)
LOCAL_MODULE := libGLESv2_open_adreno200
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
LOCAL_MODULE_TAGS := optional

LOCAL_PRELINK_MODULE := false

# Add flags
LOCAL_CFLAGS := 

# Add source files
LOCAL_SRC_FILES := 


LOCAL_C_INCLUDES := \
$(LOCAL_PATH)/../../include


LOCAL_CFLAGS += -DGLES_ERR_DEBUG




include $(BUILD_STATIC_LIBRARY)
