#!/system/bin/sh
# V6 SuperCharger, OOM Grouping & Priority Fixes created by zeppelinrox.
execute=0;
currentadj=`cat /sys/module/lowmemorykiller/parameters/adj`;
currentminfree=`cat /sys/module/lowmemorykiller/parameters/minfree`;
scadj=`cat /data/SuperChargerAdj`;
scminfree=`cat /data/SuperChargerMinfree`;
if [ "$currentadj" != "$scadj" ]; then
	execute=1;
elif [[ -n "$scminfree" ]] && [ "$currentminfree" != "$scminfree" ]; then
	execute=1;
fi;
if [ "$execute" -eq 1 ]; then
	echo $scadj > /sys/module/lowmemorykiller/parameters/adj;
	echo $scminfree > /sys/module/lowmemorykiller/parameters/minfree;
	echo "0" > /proc/sys/vm/oom_kill_allocating_task;
	echo "0" > /proc/sys/vm/panic_on_oom;
	busybox sysctl -w kernel.panic_on_oops=1;
	busybox sysctl -w kernel.panic=0;
fi;
sh /data/99SuperCharger.sh;
